let matchDetails = [
    {
      id: 1,
      homeTeam: "SOU",
      awayTeam: "MUN",
      date: "SEP 14",
      time: "17:00",
      homeLogo: "../Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Live",
    },
    {
      id: 2,
      homeTeam: "LIV",
      awayTeam: "CHE",
      date: "SEP 15",
      time: "20:00",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Upcoming",
    },
    {
      id: 3,
      homeTeam: "ARS",
      awayTeam: "TOT",
      date: "SEP 12",
      time: "18:30",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.pngg",
      status: "Completed",
    },
    {
      id: 4,
      homeTeam: "MCI",
      awayTeam: "EVE",
      date: "SEP 14",
      time: "19:00",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Upcoming",
    },
    {
      Fid: 5,
      homeTeam: "SOU",
      awayTeam: "MUN",
      date: "SEP 14",
      time: "17:00",
      homeLogo: "../Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Live",
    },
    {
      id: 6,
      homeTeam: "LIV",
      awayTeam: "CHE",
      date: "SEP 15",
      time: "20:00",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Upcoming",
    },
    {
      id: 7,
      homeTeam: "ARS",
      awayTeam: "TOT",
      date: "SEP 12",
      time: "18:30",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Completed",
    },
    {
      id: 8,
      homeTeam: "MCI",
      awayTeam: "EVE",
      date: "SEP 14",
      time: "19:00",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Upcoming",
    },
    {
      id: 9,
      homeTeam: "SOU",
      awayTeam: "MUN",
      date: "SEP 14",
      time: "17:00",
      homeLogo: "../Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Live",
    },
    {
      id: 10,
      homeTeam: "LIV",
      awayTeam: "CHE",
      date: "SEP 15",
      time: "20:00",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Upcoming",
    },
    {
      id: 11,
      homeTeam: "ARS",
      awayTeam: "TOT",
      date: "SEP 12",
      time: "18:30",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.pngg",
      status: "Completed",
    },
    {
      id: 12,
      homeTeam: "MCI",
      awayTeam: "EVE",
      date: "SEP 14",
      time: "19:00",
      homeLogo: "./Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Upcoming",
    },
    {
      Fid: 13,
      homeTeam: "SOU",
      awayTeam: "MUN",
      date: "SEP 14",
      time: "17:00",
      homeLogo: "../Images/football.png",
      awayLogo: "./Images/football.png",
      status: "Live",
    },
    {
      id: 14,
      homeTeam: "LIV",
      awayTeam: "CHE",
      date: "SEP 15",
      time: "20:00",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Upcoming",
    },
    {
      id: 15,
      homeTeam: "ARS",
      awayTeam: "TOT",
      date: "SEP 12",
      time: "18:30",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Completed",
    },
    {
      id: 16,
      homeTeam: "MCI",
      awayTeam: "EVE",
      date: "SEP 14",
      time: "19:00",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Upcoming",
    },
    {
      id: 17,
      homeTeam: "IND",
      awayTeam: "ARG",
      date: "SEP 14",
      time: "19:00",
      homeLogo: "../Images/football.png",
      awayLogo: "../Images/logo.png",
      status: "Live",
    },
  ];
export const data=()=>{
return matchDetails
}